name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pycodestyle and pydocstyle
        run: |
          python -m pip install --upgrade pip
          pip install pydocstyle pycodestyle
      - name: Running pycodestyle
        run: |
          pycodestyle $(git ls-files '*.py' | grep -v 'docs/')
      - name: Running pydocstyle
        run: |
          pydocstyle $(git ls-files '*.py' | grep -v 'docs/')
