name: unit_tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy ase matplotlib mp_api pymbar optimade
          pip install asap3
      - name: Running tests
        run: |
          pytest
